export interface Service {
  id: string;
  title: string;
  slug: string;
  category: 'clinical' | 'vaccination' | 'travel' | 'prescribing' | 'medication' | 'children' | 'testing' | 'womens-health' | 'lifestyle' | 'certificates' | 'additional' | 'weight-loss';
  description: string;
  fullDescription?: string;
  image?: string;
  price?: string;
  bookingUrl?: string;
  features?: string[];
}

const allServices: Service[] = [
  // 🩺 Clinical & Health Services
{
  id: 'blood-pressure-checks',
  title: 'Blood Pressure Checks',
  slug: '/Services/blood-pressure-checks',
  category: 'clinical',
  description: 'Regular blood pressure monitoring to help manage your cardiovascular health.',
  fullDescription:
    'Our blood pressure checking service helps you monitor your cardiovascular health. Regular checks can help detect hypertension early and manage your heart health effectively.',
  image: 'https://images.unsplash.com/photo-1615486511484-92e172cc4fe0?q=80&w=500&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
},

  {
    id: 'cholesterol-testing',
    title: 'Cholesterol Testing',
    slug: '/Services/cholesterol-testing',
    category: 'clinical',
    description: 'Cholesterol level testing to assess your heart health and cardiovascular risk.',
    fullDescription: 'Get your cholesterol levels checked to assess your cardiovascular health. Our testing service helps identify risk factors and provides expert advice on managing your cholesterol levels.',
    image: 'https://images.unsplash.com/photo-1752842350772-2921657e50d7?q=80&w=400&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D' ,
  },
  {
    id: 'blood-glucose-screening',
    title: 'Blood Glucose/Diabetes Screening',
    slug: '/Services/blood-glucose-screening',
    category: 'clinical',
    description: 'Blood glucose testing and diabetes screening to monitor your blood sugar levels.',
    fullDescription: 'Regular blood glucose screening helps detect diabetes early and monitor existing conditions. Our service provides accurate testing with expert interpretation and advice.',
    image: 'https://plus.unsplash.com/premium_photo-1702599120667-d86c2eb51ada?q=80&w=400&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    id: 'hba1c-testing',
    title: 'HbA1c Testing',
    slug: '/Services/hba1c-testing',
    category: 'clinical',
    description: 'HbA1c testing for long-term blood glucose monitoring and diabetes management.',
    fullDescription: 'HbA1c testing provides a measure of your average blood glucose levels over the past 2-3 months, essential for diabetes diagnosis and management.',
    image: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=400&h=300&fit=crop',
  },
  {
    id: 'bmi-weight-management',
    title: 'BMI & Weight Management Support',
    slug: '/Services/bmi-weight-management',
    category: 'clinical',
    description: 'BMI assessment and personalized weight management support and advice.',
    fullDescription: 'Get your BMI calculated and receive expert advice on weight management. Our pharmacists can provide personalized support to help you achieve and maintain a healthy weight.',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
  },
  {
    id: 'private-health-checks',
    title: 'Private Health Assessments (Health MOTs)',
    slug: '/Services/private-health-checks',
    category: 'clinical',
    description: 'Comprehensive private health assessments to monitor and manage your wellbeing.',
    fullDescription: 'Our comprehensive private health check services provide advanced screening to help you monitor and manage your wellbeing. We offer a range of health assessments tailored to your needs, including blood pressure monitoring, cholesterol checks, diabetes screening, and more. Book your appointment to take proactive steps towards optimal health.',
    features: [
      'Comprehensive health assessments',
      'Blood pressure monitoring',
      'Cholesterol and diabetes screening',
      'Personalized health reports',
      'Expert pharmacist consultations',
    ],
    image: 'https://images.unsplash.com/photo-1758691462123-8a17ae95d203?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aGVhbHRoJTIwYXNzZXNzbWVudHxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
  id: 'blood-test',
  title: 'Private Blood Test',
  slug: '/Services/blood-tests',
  category: 'testing',
  description: 'Private blood testing for general health, diagnostics, and screening.',
  fullDescription: 'We offer a wide range of private blood tests including Full Blood Count (FBC), liver function, kidney function, hormone panels, and general health checks. Fast and confidential results.',
  image: 'https://images.unsplash.com/photo-1714642596931-2293df25c4a3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aGVhbHRoJTIwYXNzZXNzbWVudHxlbnwwfHwwfHx8MA%3D%3D',
  features: [
    'Full Blood Count (FBC)',
    'Liver & Kidney Function Tests',
    'Hormone Panels',
    'General Health Blood Tests'
  ]
},


  // 💉 Vaccinations & Immunisation
  {
    id: 'flu-vaccination',
    title: 'Flu Vaccination',
    slug: '/Services/flu-vaccination',
    category: 'vaccination',
    description: 'Annual flu jab in Canterbury to cut your risk of serious illness, time off work, and spreading flu to others.',
    fullDescription: 'Influenza changes every year, so an up-to-date vaccine is the best defence. At OH Health + Pharmacy we offer seasonal flu vaccination with a quick consultation, answers to your questions, and aftercare advice. Ask us about eligibility for NHS-funded doses versus private booking if you prefer a flexible appointment.',
    image: 'https://images.unsplash.com/photo-1691139600731-7232eaa980c3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Zmx1JTIwdmFjY2luYXRpb258ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'yellow-fever-vaccine',
    title: 'Yellow Fever Vaccine',
    slug: '/Vaccines/yellow-fever-vaccine',
    category: 'vaccination',
    description: 'Yellow fever vaccination for travel to certain countries.',
    fullDescription: 'Yellow fever vaccination is required for travel to many countries in Africa and South America. Book your appointment to get protected.',
    image: 'https://plus.unsplash.com/premium_photo-1661719866307-c47f83c1d6ca?q=80&w=400&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    id: 'hepatitis-a',
    title: 'Hepatitis A Vaccine',
    slug: '/Vaccines/hepatitis-a-vaccine',
    category: 'vaccination',
    description: 'Hepatitis A vaccination for travel protection.',
    fullDescription: 'Hepatitis A vaccination protects against hepatitis A virus, commonly recommended for travel to certain destinations.',
    image: 'https://media.istockphoto.com/id/1130140769/photo/hepatits-a-vaccine-in-a-glass-vial.webp?a=1&b=1&s=612x612&w=0&k=20&c=5m43nR6VPO7UGhCDlH_3zfDkhz4ns8y-Jiesx-vQcL4=',
  },
  {
    id: 'hepatitis-b',
    title: 'Hepatitis B Vaccine',
    slug: '/Vaccines/hepatitis-b-vaccine',
    category: 'vaccination',
    description: 'Hepatitis B vaccination for protection against hepatitis B virus.',
    fullDescription: 'Hepatitis B vaccination provides protection against the hepatitis B virus, recommended for travel and occupational health.',
    image: 'https://media.istockphoto.com/id/954825080/photo/hepatitis-b-immunization.webp?a=1&b=1&s=612x612&w=0&k=20&c=sr07zfZImbn572r4DcHw9mJTviC2QuCBQ5Mga3rTQZ8=',
  },
  {
    id: 'typhoid',
    title: 'Typhoid Vaccine',
    slug: '/Vaccines/typhoid-vaccine',
    category: 'vaccination',
    description: 'Typhoid vaccination for travel protection.',
    fullDescription: 'Typhoid vaccination is recommended for travel to areas where typhoid fever is common, particularly parts of Asia, Africa, and South America.',
    image: 'https://images.unsplash.com/photo-1668874896975-7f874c90600a?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHR5cGhvaWQlMjB2YWNjaW5lfGVufDB8fDB8fHww',
  },
  {
    id: 'chickenpox-vaccine',
    title: 'Chickenpox Vaccine',
    slug: '/Vaccines/chickenpox-vaccine',
    category: 'vaccination',
    description: 'Private varicella vaccine for adults and children who are susceptible — ideal before pregnancy, travel, or healthcare roles.',
    fullDescription: 'Chickenpox (varicella) can be severe in adults and in pregnancy. Our team discusses your history, explains the schedule (often two doses), and administers the vaccine in a calm clinic setting. We cover common side effects and when to seek help so you feel confident from booking to follow-up.',
    image: 'https://images.unsplash.com/photo-1606619353143-8e11b4bdf76b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGNoaWNrZW5wb3glMjB2YWNjaW5lfGVufDB8fDB8fHww',
  },
  {
    id: 'hpv',
    title: 'HPV Vaccination',
    slug: '/Vaccines/hpv-vaccination',
    category: 'vaccination',
    description: 'HPV immunisation against strains linked to cervical, anal, and some throat cancers — available for eligible adults and catch-up where appropriate.',
    fullDescription: 'HPV remains the leading preventable cause of cervical cancer and contributes to other cancers and genital warts. We provide private HPV vaccination with clear guidance on dose schedules, intervals if you are partway through a course, and how the vaccine complements rather than replaces cervical screening.',
    image: 'https://plus.unsplash.com/premium_photo-1661594551472-826bdbdb09a5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aHB2JTIwdmFjY2luZXxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'shingles',
    title: 'Shingles Vaccine',
    slug: '/Vaccines/shingles-vaccine',
    category: 'vaccination',
    description: 'Reduce the risk of shingles and post-herpetic neuralgia with private shingles vaccination for eligible adults.',
    fullDescription: 'Shingles develops when the chickenpox virus reactivates, often with painful rash and sometimes long-lasting nerve pain. We assess suitability (including age and medical history), explain the benefits and common short-lived side effects, and arrange vaccination with practical aftercare tips.',
    image: 'https://plus.unsplash.com/premium_photo-1661769644240-da282f078bc1?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aHB2JTIwdmFjY2luZXxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'mmr-private',
    title: 'MMR (Private)',
    slug: '/Vaccines/mmr-vaccine',
    category: 'vaccination',
    description: 'Private MMR (Measles, Mumps, Rubella) vaccination.',
    fullDescription: 'MMR vaccination protects against measles, mumps, and rubella. Available privately for those who need it.',
    image: 'https://plus.unsplash.com/premium_photo-1668487826892-bf471b01e5ed?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bW1yJTIwdmFjY2luZXxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'meningitis-acwy',
    title: 'Meningitis ACWY',
    slug: '/Vaccines/meningitis-acwy-vaccine',
    category: 'vaccination',
    description: 'Conjugate vaccine against meningococcal groups A, C, W, and Y — required for many travellers and pilgrims, including Hajj and Umrah.',
    fullDescription: 'Meningococcal disease can progress rapidly. ACWY vaccination is recommended for teenagers, university starters, certain travellers, and pilgrimage entry requirements. We provide the injection, document your batch details for certificates where needed, and advise on MenB and general meningitis awareness separately so your protection strategy is complete.',
    bookingUrl: 'https://www.treatlocal.co.uk/online-booking/sidcup/hajj-umrah-vaccine/appointment',
    image: 'https://images.unsplash.com/photo-1576765608622-067973a79f53?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1lbmluZ2ludGlzJTIwdmFjY2luZXxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'meningitis-b',
    title: 'Meningitis B Vaccine',
    slug: '/Vaccines/meningitis-b-vaccine',
    category: 'vaccination',
    description: 'Bexsero-based protection against meningococcal group B — important for infants, young people, and those who missed routine doses.',
    fullDescription:
      'MenB is a leading cause of meningitis in the UK. We explain the licensed schedule (often multiple doses depending on age), timing with other vaccines, and normal responses such as fever in babies so you can plan calmly. Book for a private course tailored to age and any previous MenB history.',
    image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=400&auto=format&fit=crop&q=60',
  },
  {
    id: 'covid-vaccination',
    title: 'Covid-19 Private Vaccinations',
    slug: '/Travel-Clinic/private-covid-vaccination-service',
    category: 'vaccination',
    description: 'Private COVID-19 booster or primary course when offered — convenient appointments for travel, work, or added peace of mind.',
    fullDescription: 'Coronavirus still causes serious illness in vulnerable people and disrupts travel and plans. When private supply is available, we walk you through product choice, contraindications, and expected side effects. You receive documentation suitable for employers or airlines where vaccination proof is requested.',
    image: 'https://images.unsplash.com/photo-1608326389417-d3f9cc46de04?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fG1lbmluZ2ludGlzJTIwdmFjY2luZXxlbnwwfHwwfHx8MA%3D%3D',
  },

  // 🌍 Travel Health Services
  {
    id: 'travel-clinic',
    title: 'Travel Health Consultation',
    slug: '/Travel-Clinic/travel-vaccination',
    category: 'travel',
    description: 'Personalised pre-travel consult: country risks, vaccines, malaria prevention, and safer travel tips in one visit.',
    fullDescription: 'Tell us your itinerary, medical history, and departure date. We cross-check malaria risk, vaccine validity windows, and any outbreak notices, then outline a clear plan — what to have now, what can wait, and travel essentials from upset-stomach kits to bite avoidance. Our goal is sensible protection with minimal fuss before you fly.',
    features: [
      'Expert Travel Health Advice',
      'Wide range of travel vaccines',
      'Friendly and efficient service',
    ],
    bookingUrl: 'https://www.treatlocal.co.uk/online-booking/sidcup/travel-vaccine/appointment',
    image: 'https://images.unsplash.com/photo-1758691461957-474a7686e388?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fG1lZGljYWwlMjBjb25zdWx0YXRpb258ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'antimalarials',
    title: 'Anti-malaria Medication',
    slug: '/Travel-Clinic/antimalarials-sidcup',
    category: 'travel',
    description: 'Prescription-review and supply of chemoprophylaxis matched to your destination, trip length, and health profile.',
    fullDescription: 'Malaria mosquitoes bite mainly from dusk to dawn; the right tablets depend on regional resistance patterns and whether you take other medicines. We explain how to start before travel, stick to timing in new time zones, and what to do if vomiting disrupts a dose — plus non-drug bite prevention that still matters alongside tablets.',
    image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWVkaWNhdGlvbnxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'travel-vaccination-certificates',
    title: 'Travel Vaccination Certificates',
    slug: '/Travel-Clinic/travel-vaccination-certificates',
    category: 'travel',
    description: 'Official travel vaccination certificates for your travel documentation.',
    fullDescription: 'Get official travel vaccination certificates for countries that require proof of vaccination. We provide proper documentation for all travel vaccinations.',
    image: 'https://images.unsplash.com/photo-1615631648086-325025c9e51e?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dmFjY2luYXRpb258ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'travel-health-packs',
    title: 'Travel Health Packs and Advice',
    slug: '/Travel-Clinic/travel-health-packs',
    category: 'travel',
    description: 'Comprehensive travel health packs and expert travel health advice.',
    fullDescription: 'Get prepared for your trip with our travel health packs containing essential medications and supplies. Our expert pharmacists provide personalized travel health advice.',
    image: 'https://images.unsplash.com/photo-1539635278303-d4002c07eae3?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D',
  },

  // 📄 Private Prescribing & Consultations
  {
    id: 'private-gp-consultations',
    title: 'Private GP-style Consultations',
    slug: '/Services/private-gp-consultations',
    category: 'prescribing',
    description: 'Private GP-style consultations for various health conditions.',
    fullDescription: 'Access private GP-style consultations at our pharmacy. Our qualified prescribers can assess and treat a range of common health conditions.',
    image: 'https://images.unsplash.com/photo-1758273240403-052b3c99f636?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cHJpdmF0ZSUyMGNvbnN1bHRhdGlvbnxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'uti-treatment',
    title: 'UTI Treatment',
    slug: '/Services/uti-treatment',
    category: 'prescribing',
    description: 'Expert assessment and treatment for urinary tract infections.',
    fullDescription: 'Get fast and effective treatment for urinary tract infections through our pharmacist prescriber service. Quick assessment and appropriate treatment available.',
    image: 'https://images.unsplash.com/photo-1637000289497-f5d424b696a6?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHVyaW5lfGVufDB8fDB8fHww',
  },
  {
    id: 'ear-infections',
    title: 'Ear Infections',
    slug: '/Services/ear-infections',
    category: 'prescribing',
    description: 'Pharmacist-led assessment for acute otitis media and outer-ear infections with NHS-style clinical checks where appropriate.',
    fullDescription: 'Painful ears can be outer canal infections (swimmer’s ear), middle-ear infections after colds, or wax-related pressure. Our independent prescribers take a focused history, advise on red-flag symptoms, and supply proven ear drops or other treatments when suitable. You leave with a clear plan: symptom relief, expected recovery time, and when to seek urgent care.',
    image: 'https://plus.unsplash.com/premium_photo-1661779725491-e997e70928fc?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGVhciUyMGluZmVjdGlvbnxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'sore-throat-assessment',
    title: 'Sore Throat Assessment',
    slug: '/Services/sore-throat-assessment',
    category: 'prescribing',
    description: 'Professional assessment and treatment for sore throats.',
    fullDescription: 'Get expert assessment and treatment for sore throats. Our pharmacists can determine if antibiotics are needed or provide advice on symptom relief.',
    image: 'https://plus.unsplash.com/premium_photo-1661779425660-33e91cce9dd4?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c29yZSUyMHRocm9hdHxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'skin-conditions',
    title: 'Skin Conditions (Eczema, Acne, Psoriasis)',
    slug: '/Services/skin-conditions',
    category: 'prescribing',
    description: 'Targeted prescribing for flares of acne, eczema, and mild-to-moderate plaque-derived psoriasis after a structured assessment.',
    fullDescription: 'Skin flare-ups affect sleep, confidence, and daily comfort. We review pattern, triggers, and what you have already tried, then supply evidence-based topicals or short courses where guidelines support them — plus emollient routines and gentle skincare habits so treatment lasts beyond the prescription. We are clear about when a GP or dermatology review is safer.',
    image: 'https://images.unsplash.com/photo-1730288951113-9cc087c14b83?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2tpbiUyMGNvbmRpdGlvbnxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'contraception',
    title: 'Contraception (Pill, Patch, Injection)',
    slug: '/Services/contraception',
    category: 'prescribing',
    description: 'Comprehensive contraception services including pill, patch, and injection options.',
    fullDescription: 'Access expert contraception services including the pill, patch, and injection. Our pharmacist prescribers can help you find the right contraceptive method for your needs.',
    image: 'https://images.unsplash.com/photo-1522422263604-6c2ac26bfdf7?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGNvbnRyYWNlcHRpb258ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'erectile-dysfunction',
    title: 'Erectile Dysfunction',
    slug: '/Services/erectile-dysfunction',
    category: 'prescribing',
    description: 'Discreet consultation for erectile difficulty — exploring cardiovascular safety, lifestyle factors, and suitable PDE5 therapy.',
    fullDescription: 'ED is common and sometimes an early clue to blood pressure or blood-sugar issues. We conduct a confidential health review, discuss medicines that must not mix with certain tablets, and explain dosing, food effects, and realistic expectations. Follow-up focuses on whether symptoms improved and whether your GP should investigate underlying causes.',
    image: 'https://images.unsplash.com/photo-1580281657527-47f249e8f4df?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cGhhcm1hY3l8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'asthma-inhaler-refills',
    title: 'Asthma Inhaler Refills (Private)',
    slug: '/Services/asthma-inhaler-refills',
    category: 'prescribing',
    description: 'Private asthma inhaler refills and asthma management support.',
    fullDescription: 'Get private asthma inhaler refills and expert advice on asthma management. Our pharmacists can help ensure you have the right inhaler and technique.',
    image: 'https://images.unsplash.com/photo-1637930030080-4ec4b95914c0?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aW5oYWxlcnxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'migraine-treatment',
    title: 'Migraine Treatment',
    slug: '/Services/migraine-treatment',
    category: 'prescribing',
    description: 'Assessment of episodic migraine with acute symptom relief and, where suitable, preventive options — plus trigger diary coaching.',
    fullDescription: 'We distinguish migraine from headaches that need urgent referral, review frequency and impact on work, and agree a rescue plan (including nausea management when needed). You receive pragmatic advice on sleep, caffeine, hydration, and medication-overuse headaches so short-term relief does not accidentally prolong the problem.',
    image:'https://images.unsplash.com/photo-1619694108677-8a4dc3bd9875?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fG1pZ3JhaW5lJTIwdHJlYXRtZW50fGVufDB8fDB8fHww',
  },
  {
    id: 'hay-fever-treatments',
    title: 'Hay Fever Treatments',
    slug: '/Services/hay-fever-treatments',
    category: 'prescribing',
    description: 'Expert advice and treatment for hay fever and seasonal allergies.',
    fullDescription: 'Get relief from hay fever symptoms with expert advice and treatment. Our pharmacists can recommend the best treatment options for your hay fever.',
    image: 'https://plus.unsplash.com/premium_photo-1661537390414-33d7ad495159?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aGF5JTIwZmV2ZXIlMjB0cmVhdG1lbnR8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'weight-loss-medication',
    title: 'Weight-loss Medication Consultations (Wegovy, Saxenda)',
    slug: '/Services/weight-loss-medication',
    category: 'prescribing',
    description: 'Consultations for weight-loss medications including Wegovy and Saxenda.',
    fullDescription: 'Get expert consultations for weight-loss medications including Wegovy and Saxenda. Our pharmacist prescribers can assess your eligibility and provide appropriate treatment.',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
  },

  // 💊 Medication-Related Services
  {
    id: 'private-prescriptions',
    title: 'Private Prescription Dispensing',
    slug: '/Services/private-prescriptions',
    category: 'medication',
    description: 'Private prescription dispensing services available at our pharmacy.',
    fullDescription: 'We offer private prescription services for your convenience. Fast and efficient dispensing of private prescriptions.',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=300&fit=crop',
  },
  {
    id: 'repeat-prescription-collection',
    title: 'Repeat Prescription Collection & Delivery',
    slug: '/Services/repeat-prescription-collection',
    category: 'medication',
    description: 'Convenient repeat prescription collection and delivery service.',
    fullDescription: 'Save time with our repeat prescription collection and delivery service. We can collect your prescriptions from your GP and deliver them to your door.',
    image: 'https://images.unsplash.com/photo-1576091358783-a212ec293ff3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cHJlc2NyaXB0aW9ufGVufDB8fDB8fHww',
  },
  {
    id: 'emergency-supply',
    title: 'Emergency Supply of Medicines',
    slug: '/Services/emergency-supply',
    category: 'medication',
    description: 'Emergency supply of medicines when you run out of your regular medication.',
    fullDescription: 'If you run out of your regular medication, we may be able to provide an emergency supply. Our pharmacists can assess your situation and provide appropriate assistance.',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cHJlc2NyaXB0aW9ufGVufDB8fDB8fHww',
  },
  {
    id: 'morning-after-pill',
    title: 'Morning-After Pill (EHC)',
    slug: '/Services/morning-after-pill',
    category: 'medication',
    description: 'Emergency contraception (morning-after pill) available at our pharmacy.',
    fullDescription: 'Emergency contraception (morning-after pill) is available at our pharmacy. Our trained staff provide confidential and professional service.',
    image: '/images/contraception.jpg',
  },
  {
    id: 'specialist-medicines',
    title: 'Specialist Medicines Ordering',
    slug: '/Services/specialist-medicines',
    category: 'medication',
    description: 'Ordering service for specialist and hard-to-find medicines.',
    fullDescription: 'We can help you source specialist and hard-to-find medicines. Our ordering service ensures you get the medications you need.',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=300&fit=crop',
  },
  {
    id: 'travel-medication',
    title: 'Travel Medication Supply',
    slug: '/Services/travel-medication',
    category: 'medication',
    description: 'Travel-health medicines such as altitude-sickness prophylaxis, jet-lag melatonin advice, and gastro kits — professionally screened for interactions.',
    fullDescription: 'Beyond vaccines, many trips need tablets for motion sickness, traveller’s diarrhoea, sleep disruption, or altitude. We check your NHS and private prescriptions for clashes, explain dosing around flights, and prioritise compact kits so you are prepared without over-packing. If something needs a prescriber, we route you to the right clinic pathway.',
    image: 'https://images.unsplash.com/photo-1539635278303-d4002c07eae3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D',
  },

  // 👶 Children & Family Services
  {
    id: 'childhood-vaccinations',
    title: 'Childhood Vaccinations (Private)',
    slug: '/Services/childhood-vaccinations',
    category: 'children',
    description: 'Private childhood vaccinations for your children.',
    fullDescription: 'Access private childhood vaccinations for your children. We provide a range of childhood vaccines in a friendly and comfortable environment.',
    image: 'https://plus.unsplash.com/premium_photo-1691752881339-d78da354ee7e?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2hpbGRyZW58ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'head-lice-treatment',
    title: 'Head Lice Advice and Treatment',
    slug: '/Services/head-lice-treatment',
    category: 'children',
    description: 'Expert advice and treatment for head lice.',
    fullDescription: 'Get expert advice and effective treatment for head lice. Our pharmacists can recommend the best treatment options and provide guidance on prevention.',
    image: 'https://images.unsplash.com/photo-1540479859555-17af45c78602?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpbGRyZW58ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'newborn-health-support',
    title: 'Colic, Feeding, and Newborn Health Support',
    slug: '/Services/newborn-health-support',
    category: 'children',
    description: 'Expert advice and support for colic, feeding, and newborn health concerns.',
    fullDescription: 'Get expert advice and support for colic, feeding issues, and newborn health concerns. Our pharmacists provide guidance to help new parents.',
    image: 'https://plus.unsplash.com/premium_photo-1664474430762-f5201ecb6c43?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bmV3Ym9ybnxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'child-ear-infection',
    title: 'Child Ear Infection / Sore Throat Assessment',
    slug: '/Services/child-ear-infection',
    category: 'children',
    description: 'Assessment and treatment for children\'s ear infections and sore throats.',
    fullDescription: 'Expert assessment and treatment for children\'s ear infections and sore throats. Our pharmacist prescribers can provide appropriate care for your child.',
    image: 'https://plus.unsplash.com/premium_photo-1723489239811-7abaa1301cb8?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y2hpbGQlMjBlYXJ8ZW58MHx8MHx8fDA%3D',
  },

  // 🧪 Testing & Screening Services
  {
    id: 'std-sti-testing',
    title: 'STD / STI Testing',
    slug: '/Services/std-sti-testing',
    category: 'testing',
    description: 'Confidential STD/STI testing for chlamydia, gonorrhoea, HIV, and syphilis.',
    fullDescription: 'Get confidential STD/STI testing including chlamydia, gonorrhoea, HIV, and syphilis. Our service is discreet and professional.',
    image: 'https://plus.unsplash.com/premium_photo-1668487827156-7aa259d7ffa3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dGVzdGluZ3xlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'hiv-testing',
    title: 'Private HIV Testing',
    slug: '/Services/hiv-testing',
    category: 'testing',
    description: 'Private HIV testing available as rapid or lab-based tests.',
    fullDescription: 'Access private HIV testing with rapid or lab-based options. Our service is confidential and provides expert support and guidance.',
    image: 'https://images.unsplash.com/photo-1579165466991-467135ad3110?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHRlc3Rpbmd8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'thyroid-function-test',
    title: 'Thyroid Function Test',
    slug: '/Services/thyroid-function-test',
    category: 'testing',
    description: 'Thyroid function testing to assess thyroid health.',
    fullDescription: 'Get your thyroid function tested to assess your thyroid health. Our testing service helps detect thyroid disorders early.',
    image: 'https://plus.unsplash.com/premium_photo-1668487827156-7aa259d7ffa3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dGVzdGluZ3xlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'vitamin-d-testing',
    title: 'Vitamin D Testing',
    slug: '/Services/vitamin-d-testing',
    category: 'testing',
    description: 'Vitamin D level testing to assess your vitamin D status.',
    fullDescription: 'Get your vitamin D levels tested to assess your status. Low vitamin D can affect bone health and overall wellbeing.',
    image: 'https://plus.unsplash.com/premium_photo-1676325102275-f5ec2de6c971?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fHRlc3Rpbmd8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'allergy-testing',
    title: 'Allergy Testing',
    slug: '/Services/allergy-testing',
    category: 'testing',
    description: 'Allergy testing to identify allergens and manage allergic reactions.',
    fullDescription: 'Get tested for allergies to identify triggers and manage allergic reactions. Our testing service helps you understand your allergies better.',
    image: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=400&h=300&fit=crop',
  },
  {
    id: 'hormone-testing',
    title: 'Hormone Testing (Testosterone, Fertility, Menopause)',
    slug: '/Services/hormone-testing',
    category: 'testing',
    description: 'Comprehensive hormone testing for testosterone, fertility, and menopause.',
    fullDescription: 'Get comprehensive hormone testing including testosterone, fertility hormones, and menopause-related hormones. Our testing helps assess hormonal health.',
    image: 'https://images.unsplash.com/photo-1601961545517-59307b1fbac3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHRlc3Rpbmd8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'kidney-liver-function',
    title: 'Kidney and Liver Function Tests',
    slug: '/Services/kidney-liver-function',
    category: 'testing',
    description: 'Kidney and liver function testing to monitor organ health.',
    fullDescription: 'Get your kidney and liver function tested to monitor organ health. These tests help detect potential issues early.',
    image: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=400&h=300&fit=crop',
  },
  {
    id: 'coeliac-testing',
    title: 'Coeliac Testing',
    slug: '/Services/coeliac-testing',
    category: 'testing',
    description: 'Coeliac disease testing to diagnose gluten intolerance.',
    fullDescription: 'Get tested for coeliac disease to diagnose gluten intolerance. Our testing service helps identify if you have coeliac disease.',
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRlc3Rpbmd8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'covid-testing',
    title: 'Covid-19 PCR / Antigen Tests',
    slug: '/Services/covid-testing',
    category: 'testing',
    description: 'Covid-19 PCR and antigen testing available.',
    fullDescription: 'Get Covid-19 PCR or antigen tests for travel, work, or peace of mind. Fast and accurate testing available.',
    image: 'https://plus.unsplash.com/premium_photo-1661440247844-f28df59bcc5b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y292aWQlMjB0ZXN0aW5nfGVufDB8fDB8fHww',
  },
  {
    id: 'workplace-drug-testing',
    title: 'Workplace Drug Testing',
    slug: '/Services/workplace-drug-testing',
    category: 'testing',
    description: 'Workplace drug testing services available at some pharmacies.',
    fullDescription: 'Workplace drug testing services available. Contact us for more information about this service.',
    image: 'https://images.unsplash.com/photo-1615631898182-0f6550dd2fbd?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y292aWQlMjB0ZXN0aW5nfGVufDB8fDB8fHww',
  },
  // 🏥 Women's Health Services
  {
    id: 'thrush-bv-treatment',
    title: 'Thrush / BV Treatment',
    slug: '/Services/thrush-bv-treatment',
    category: 'womens-health',
    description: 'Expert treatment for thrush and bacterial vaginosis (BV).',
    fullDescription: 'Get effective treatment for thrush and bacterial vaginosis (BV). Our pharmacists provide expert advice and appropriate treatment options.',
    image: 'https://plus.unsplash.com/premium_photo-1668605109201-2dcf7a001215?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZHJ1Z3xlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'menopause-consultations',
    title: 'Menopause Consultations',
    slug: '/Services/menopause-consultations',
    category: 'womens-health',
    description: 'Expert consultations and support for menopause symptoms.',
    fullDescription: 'Get expert consultations and support for menopause symptoms. Our pharmacists can provide advice on managing menopause and available treatments.',
    image: 'https://images.unsplash.com/photo-1739285388427-d6f85d12a8fc?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWVkaWNhbCUyMGNvbnN1bHRhdGlvbnxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'pregnancy-testing',
    title: 'Pregnancy Testing',
    slug: '/Services/pregnancy-testing',
    category: 'womens-health',
    description: 'Pregnancy testing available at our pharmacy.',
    fullDescription: 'Get accurate pregnancy testing at our pharmacy. Our trained staff provide confidential and professional service.',
    image: 'https://images.unsplash.com/flagged/photo-1572531186838-27a5459566f2?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cHJlZ25hbmN5fGVufDB8fDB8fHww',
  },

  // 🍃 Lifestyle & Wellness Services
  {
    id: 'stop-smoking',
    title: 'Smoking Cessation Programs',
    slug: '/Services/stop-smoking',
    category: 'lifestyle',
    description: 'Expert advice and support to help you quit smoking.',
    fullDescription: 'Our Stop Smoking Service is designed to help you quit smoking through expert advice and Nicotine replacement products. Our trained pharmacists can provide personalized support and guidance to help you on your journey to becoming smoke-free.',
    features: [
      'Expert pharmacist consultations',
      'Nicotine replacement products',
      'Personalized quit plans',
      'Ongoing support and advice',
      'Proven success strategies',
    ],
    image: 'https://plus.unsplash.com/premium_photo-1667680761053-650123c814f7?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c21va2luZ3xlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'weight-loss',
    title: 'Weight-loss Services & Medication',
    slug: '/weight-loss-service',
    category: 'weight-loss',
    description: 'Medically supervised GLP-1 style programme in Canterbury with onboarding checks, injections or supply as approved, and habit coaching.',
    fullDescription: 'Obesity increases strain on joints, blood sugar, and heart health — sustainable change needs more than willpower. We provide eligibility screening (BMI, medical history, medicines), clinician oversight where required, and structured check-ins at the pharmacy. You get practical diet and movement lessons alongside medication where appropriate, plus dashboard tracking so progress is visible between visits.',
    features: [
      'Online consultations',
      'Diet and exercise advice',
      'Regular check-in appointments',
      'Patient dashboard to track progress',
      'Comprehensive support throughout the programme',
    ],
    bookingUrl: 'https://expertweightloss.co.uk/booking/injection/clinic/sidcup',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGZpdG5lc3N8ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'alcohol-reduction',
    title: 'Alcohol Reduction Support',
    slug: '/Services/alcohol-reduction',
    category: 'lifestyle',
    description: 'Expert support and advice for reducing alcohol consumption.',
    fullDescription: 'Get expert support and advice for reducing alcohol consumption. Our pharmacists can provide guidance and resources to help you reduce your alcohol intake.',
    image: 'https://images.unsplash.com/photo-1508253730651-e5ace80a7025?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YWxjb2hvbHxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'healthy-lifestyle-coaching',
    title: 'Healthy Lifestyle Coaching',
    slug: '/Services/healthy-lifestyle-coaching',
    category: 'lifestyle',
    description: 'Personalized healthy lifestyle coaching and advice.',
    fullDescription: 'Get personalized healthy lifestyle coaching and advice. Our pharmacists can help you develop healthy habits and improve your overall wellbeing.',
    image: 'https://images.unsplash.com/photo-1556911073-a517e752729c?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aGVhbHRoeSUyMGxpZmVzdHlsZXxlbnwwfHwwfHx8MA%3D%3D', 
  },
  {
    id: 'vitamin-b12',
    title: 'Vitamin B12 Injections',
    slug: '/Services/vitamin-b12',
    category: 'lifestyle',
    description: 'Private vitamin B12 injections, with care from the OH Health+ Pharmacy team.',
    fullDescription: 'Vitamin B12 supports normal energy metabolism and nervous system function. We offer a private vitamin B12 injection service at our pharmacy. Book your appointment online.',
    price: '£29',
    bookingUrl: 'https://www.treatlocal.co.uk/online-booking/sidcup/vitamin-b12-injection-service/appointment',
    image: 'https://plus.unsplash.com/premium_photo-1673953886109-a3249821993d?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aW5qZWN0aW9ufGVufDB8fDB8fHww',
  },
  {
    id: 'earwax-removal',
    title: 'Earwax Removal',
    slug: '/Services/earwax-removal-service',
    category: 'lifestyle',
    description: 'Microsuction earwax removal service. Safe and professional.',
    fullDescription: 'We offer a private microsuction earwax removal service in Canterbury at OH Health + Pharmacy. Book your appointment online.',
    image: 'https://images.unsplash.com/photo-1741174844812-c59239e677be?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZWFyJTIwd2F4JTIwcmVtb3ZhbHxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    id: 'sports-injury-advice',
    title: 'Sports Injury Advice',
    slug: '/Services/sports-injury-advice',
    category: 'lifestyle',
    description: 'Expert advice and support for sports injuries.',
    fullDescription: 'Get expert advice and support for sports injuries. Our pharmacists can provide guidance on managing sports injuries and recommend appropriate treatments.',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c3BvcnR8ZW58MHx8MHx8fDA%3D',
  },

  // 📑 Certificates & Workplace Services
  {
    id: 'fit-to-fly',
    title: 'Fit-to-fly Certificates',
    slug: '/Services/fit-to-fly',
    category: 'certificates',
    description: 'Fit-to-fly medical certificates for air travel.',
    fullDescription: 'Get fit-to-fly medical certificates for air travel. Our service provides the necessary documentation for your travel needs.',
    image: 'https://images.unsplash.com/photo-1570610159825-ec5d3823660c?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGNlcnRpZmljYXRpb258ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'fit-to-work-medicals',
    title: 'Fit-to-work Medicals',
    slug: '/Services/fit-to-work-medicals',
    category: 'certificates',
    description: 'Fit-to-work medical examinations available at some pharmacies.',
    fullDescription: 'Fit-to-work medical examinations available. Contact us for more information about this service.',
    image: 'https://plus.unsplash.com/premium_photo-1681995460558-738a8856313c?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aGVhbHRoY2FyZSUyMGFuZCUyMG1lZGljaW5lfGVufDB8fDB8fHww',
  },
  {
    id: 'occupational-health-vaccinations',
    title: 'Occupational Health Vaccinations',
    slug: '/Services/occupational-health-vaccinations',
    category: 'certificates',
    description: 'Occupational health vaccinations for workplace requirements.',
    fullDescription: 'Get occupational health vaccinations for workplace requirements. We provide the necessary vaccinations and documentation for your job.',
    image: 'https://plus.unsplash.com/premium_photo-1661501762188-b1598949aecc?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8dmFjY2luYXRpb258ZW58MHx8MHx8fDA%3D',
  },
  {
    id: 'covid-recovery-certificates',
    title: 'Covid Recovery Certificates',
    slug: '/Services/covid-recovery-certificates',
    category: 'certificates',
    description: 'Covid recovery certificates for travel and other purposes.',
    fullDescription: 'Get Covid recovery certificates for travel and other purposes. Our service provides the necessary documentation.',
    image: 'https://images.unsplash.com/photo-1616101001234-7320af4f1aa7?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Y2VydGlmaWNhdGVzfGVufDB8fDB8fHww',
  },
  {
    id: 'private-sick-notes',
    title: 'Private Sick Notes',
    slug: '/Services/private-sick-notes',
    category: 'certificates',
    description: 'Private sick notes if provided by a prescriber.',
    fullDescription: 'Private sick notes available if provided by a prescriber. Contact us for more information.',
    image: 'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGVuJTIwYW5kJTIwcGFwZXJ8ZW58MHx8MHx8fDA%3D',
  },

  // 🔧 Additional Services
  {
    id: 'needle-sharps-disposal',
    title: 'Needle and Sharps Disposal',
    slug: '/Services/needle-sharps-disposal',
    category: 'additional',
    description: 'Safe disposal service for needles and sharps.',
    fullDescription: 'Safely dispose of needles and sharps at our pharmacy. We provide proper disposal services to keep you and others safe.',
    image: 'https://plus.unsplash.com/premium_photo-1668416938861-60bbde0598a5?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bmVlZGxlfGVufDB8fDB8fHww',
  },
  {
    id: 'mobility-aids',
    title: 'Mobility Aids and Medical Equipment Sales',
    slug: '/Services/mobility-aids',
    category: 'additional',
    description: 'Mobility aids and medical equipment available for purchase.',
    fullDescription: 'Browse our range of mobility aids and medical equipment. We stock a variety of products to support your health and mobility needs.',
    image: 'https://plus.unsplash.com/premium_photo-1661292083810-d5caa95df532?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bW9iaWxpdHklMjBhaWRzfGVufDB8fDB8fHww',
  },
  {
    id: 'eye-care',
    title: 'Eye Care',
    slug: '/eye-care',
    category: 'additional',
    description: 'High-quality spectacles at affordable prices.',
    fullDescription: 'Rifaray Eye Care offers high-quality spectacles at affordable prices. Contact our team for details.',
    image: 'https://images.unsplash.com/photo-1501621667575-af81f1f0bacc?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZXllJTIwY2FyZXxlbnwwfHwwfHx8MA%3D%3D',
  },
];

const allowedServiceIds = new Set<string>([
  'skin-conditions', // Acne
  'travel-medication', // Altitude sickness, jet lag, travellers' diarrhoea
  'chickenpox-vaccine',
  'covid-vaccination',
  'ear-infections',
  'erectile-dysfunction',
  'flu-vaccination',
  'hpv',
  'antimalarials', // Malaria
  'meningitis-acwy',
  'meningitis-b',
  'migraine-treatment',
  'shingles',
  'travel-clinic', // Travel health
  'vitamin-b12',
  'weight-loss',
]);

export const services: Service[] = allServices.filter((service) =>
  allowedServiceIds.has(service.id),
);

export const getServiceBySlug = (slug: string): Service | undefined => {
  return services.find(service => service.slug === slug);
};

export const getServicesByCategory = (category: Service['category']): Service[] => {
  return services.filter(service => service.category === category);
};

export function getAllServices() {
  return services;
};

export const getFeaturedServices = (): Service[] => {
  return services.filter(service => 
    ['vitamin-b12', 'travel-clinic', 'weight-loss', 'earwax-removal', 'eye-care', 'private-health-checks'].includes(service.id)
  );
};
